worker_processes 5;
daemon off;

worker_rlimit_nofile 8192;

events {
  worker_connections  4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen {{PORT}};
        root /app;
        
        # Ignorar o comportamento padrao do 'index' que tenta procurar na raiz
        index off;

        # 1. API - Reencaminha /api/... para /Backend/api/...
        location /api/ {
            rewrite ^/api/(.*)$ /Backend/api/$1 last;
        }

        # 2. Assets (CSS, JS, Imagens, Linguagem) - Reencaminha para /Frontend/...
        location ~ ^/(css|js|img|lang)/(.*)$ {
            rewrite ^/(css|js|img|lang)/(.*)$ /Frontend/$1/$2 last;
        }

        # 3. Raiz EXATA - Redireciona logo para o index.html do Frontend
        location = / {
            rewrite ^ /Frontend/index.html last;
        }

        # 4. Páginas HTML e outros ficheiros - Tenta no Frontend
        location / {
            rewrite ^/([^/]+\.html)$ /Frontend/$1 last;
            try_files $uri $uri/ /Frontend$uri /Frontend/index.html;
        }

        # 5. Execução segura do PHP
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
