<?php
$replacements = [
    "?<!DOCTYPE html>" => "<!DOCTYPE html>",
    "p?gina" => "página",
    "P?gina" => "Página",
    "?rea" => "Área",
    "?reas" => "Áreas",
    "Gest?o" => "Gestão",
    "Sess?o" => "Sessão",
    "A??es" => "Ações",
    "Administra??o" => "Administração",
    "Portugu?s" => "Português",
    "Fran?ais" => "Français",
    "n?o" => "não",
    "N?o" => "Não",
    "j?" => "já",
    "l?" => "lá",
    "bot?o" => "botão",
    "bot?es" => "botões",
    "liga??o" => "ligação",
    "obrigat?rios" => "obrigatórios",
    "descri??o" => "descrição",
    "Descri??o" => "Descrição",
    "T?tulo" => "Título",
    "t?tulo" => "título",
    "refer?ncia" => "referência",
    "Refer?ncia" => "Referência",
    "c?digos" => "códigos",
    "ecr?" => "ecrã",
    "n?meros" => "números",
    "A??o" => "Ação",
    "a??o" => "ação",
    "s?" => "só",
    "At?" => "Até",
    "at?" => "até",
    "est?" => "está",
    "Est?" => "Está",
    "voc?" => "você",
    "Voc?" => "Você",
    "Altera??es" => "Alterações",
    "altera??es" => "alterações",
    "Notifica??es" => "Notificações",
    "notifica??es" => "notificações",
    "Informa??o" => "Informação",
    "informa??o" => "informação",
    "Avalia??o" => "Avaliação",
    "avalia??o" => "avaliação",
    "Hist?rico" => "Histórico",
    "hist?rico" => "histórico",
    "?cones" => "ícones",
    "v?rias" => "várias",
    "V?rias" => "Várias",
    "tradu??es" => "traduções",
    "Tradu??es" => "Traduções",
    "conex?o" => "conexão",
    "Conex?o" => "Conexão",
    "padr?o" => "padrão",
    "Padr?o" => "Padrão",
    "m?nimo" => "mínimo",
    "M?nimo" => "Mínimo",
    "atrav?s" => "através",
    "Atrav?s" => "Através",
    "al?m" => "além",
    "Al?m" => "Além",
    "tamb?m" => "também",
    "Tamb?m" => "Também",
    "ent?o" => "então",
    "Ent?o" => "Então",
    "s?o" => "são",
    "S?o" => "São",
    "est?o" => "estão",
    "Est?o" => "Estão",
    "h?" => "há",
    "H?" => "Há",
    "ap?s" => "após",
    "Ap?s" => "Após",
    "pr?ximo" => "próximo",
    "Pr?ximo" => "Próximo",
    "?nico" => "único",
    "?? " => "ão ",
    "??" => "ão",
    " ? " => " é ",
    " ?a " => " ća ",
    "? que " => "à que ",
    " portugu?s " => " português ",
    "Rascunho" => "Rascunho"
];

$files = glob("*.html");
foreach ($files as $file) {
    $content = file_get_contents($file);
    foreach ($replacements as $search => $replace) {
        $content = str_replace($search, $replace, $content);
    }
    file_put_contents($file, $content);
}
echo "Fixed words in HTML files.";
?>
